### ISSUE TITLE
Will it has English translation?

### ISSUE THREAD

**Issue by xenogew** [RoMELDE/RuneBFS#12]
I'm non-Chinese player, so, want to ask you will it has translation?

I got app link from PH player. That's mean this app is go spread wide into English user.

**Comment by WindWT** [comment]
Can you provide a download link to your version of ROM? I may add other servers' data in a few days (if I have time).
(Since I'm not an active player of ROM anymore, maybe you'll need open another issue when supernovice is available on your server.)

**Comment by xenogew** [comment]
Here's the link to app of SEA version
[ROM Sea link](https://play.google.com/store/apps/details?id=com.gravity.romg)

**Comment by WindWT** [comment]
I'm sorry but things got complicated.
Since the newest client(EP6.0) have some new protection for game data, it's not possible to get data again. (And I have no time & interest to bypass the protection **again**)
Please use in-game function instead, as it has most of the function RuneBFS have.

**Comment by xenogew** [comment]
OK, thanks for your time and response.
